### ISSUE TITLE
Questions about licence, usage of OptIn and scheduler 

### ISSUE THREAD

**Issue by morki** [Scogun/kcron-common#23]
Hi @Scogun, thank you for such a great multiplatform library. I really love it, but I have some questions about using it.

## 1. Permissive Licence

It seems from the repo that this library uses GPL licence, which prohibits usage in commercial closed source software.
Would you be open for some more permissive licence like Apache or MIT?

## 2. `@OptIn(DelicateIterableApi::class)`

I really love the new `asIterable` approach, but why is now the default and only non-deprecated function OptIn?
Is there any reason behind this, which I don't see?

## 3. Scheduler in optional module

Did you consider adding some scheduler (probably based on coroutines) to this library as optional module?
Something that could be used in for example `Ktor` server like this:

```kotlin
coroutineScope {
    cron("0/10 5-25 5,12 ? * 7#5 2050") {
        // some actions
    }
}
```

**Comment by Scogun** [comment]
Hello @morki! I'm glad that my work helps other developers.
Let me answer your questions:

## 1. Permissive Licence

I guess, it's okay to switch on Apache Licence. I will more carefully check it and prepare the switching.

## 2. `@OptIn(DelicateIterableApi::class)`

The `asIterable` approach is the great improving, I agree. However, previous implementation was finite one. With `asIterable` a developer can face infinity loop in case it will not be limited by an expression or by `take`, `takeWhile` or `first` etc. function calls. So, to notify the developer about such possibility `DelicateIterableApi` was introduced. Deprecated `nextRunList` is already OptIn because it finite by `take` call.

## 3. Scheduler in optional module

Yes, I already have plans implement other libraries based on current one. I even started [kcron-job](https://github.com/Scogun/kcron-jobs) library long time ago. However, right now the plan is reorganize the project into multi module one with `kcron-core`, `kcron-common`, `kcron-job` modules etc. I'm open for any other ideas like `ktor` or `coroutines` extension.

**Comment by Scogun** [comment]
Hello @morki,

I switch the project on Apache 2.0 license. New version should appear soon.

Do you have other questions?

**Comment by morki** [comment]
Thank you very much for the licence. Is there any time estimate for coroutines job scheduler?

I was looking to the `kcron-job` library and I think it can be easily derived from function there, with some messing with coroutine scope. I am now trying to prepare some prototype of it using coroutines `delay()`.

Will try to contribute this prototype into other issue, to not mess up planned modularization.
