### ISSUE TITLE
[question] Should "asIterable()" 1st element be equal to specified start datetime?

### ISSUE THREAD

**Issue by Myshkouski** [Scogun/kcron-common#25]
Assume a cron is set to trigger every day at midnight:

```kotlin
val builder = Builder().anyDays().hours(0).minutes(0).seconds(0)
```

When `asIterable()` with start datetime of `2050-01-01T00:00:00` is called, the first element would be `2050-01-02T00:00:00` (next day), not start datetime itself:

```kotlin
val start = LocalDate(2050, 1, 1).atTime(0, 0, 0)
val expected = start
val actual = builder.asIterable(start).first()
actual.shouldBeEqual(expected) // throws java.lang.AssertionError: 2050-01-02T00:00 should be equal to 2050-01-01T00:00
```

@Scogun Should it be like that? I think before introducing `asIterable(start: LocalDateTime)` this issue had no place (current datetime always been used) and the behaviour should be changed. [This](https://github.com/Scogun/kcron-common/compare/main...Myshkouski:kcron-common:fix-iterable-first-element) change would fix the issue.

**Comment by Scogun** [comment]
Hey @Myshkouski,
This is a good catch!
However, the fix is not full. We have to compare seconds with the equal only in case the date time is **not now**.
Maybe will be better just decrise start time on one second and case it's not `now`?
Or even, we can just rename the parameter as `from` - means not include a provided value. So, in this case it will be a developer responsibility to provide `from` date a slightly earlier.
